version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      efcore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      aspnetcore:
        patterns:
          - "Microsoft.AspNetCore*"
      testing:
        patterns:
          - "xunit*"
          - "FluentAssertions"
          - "Microsoft.NET.Test.Sdk"
          - "coverlet.collector"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
